---
title: "Week 13 Lab"
author: "Manroop"
date: "04/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Libraries #
```{r}
library(tidyverse)
library(here)
```

# Looping Data #
```{r}
H_path<-here("Week_13", "Data", "homework") 

H_files <- dir(path = H_path, pattern = ".csv")  
H_data<-data.frame(matrix(nrow = length(H_files), ncol = 5)) 

colnames(H_data)<-c("filename","mean_temp", "stdev_temp", "mean_light", "stdev_light")  
```

# Making Data Frame #
```{r}
for (i in 1:length(H_files)){
  homework_data<-read_csv(paste0(H_path,"/",H_files[i])) 
  H_data$filename[i]<-H_files[i]  
  
  H_data$mean_temp[i]<-mean(homework_data$Temp.C, na.rm = TRUE) 
  H_data$stdev_temp[i] <- sd(homework_data$Temp.C, na.rm = TRUE) 
  H_data$mean_light[i]<-mean(homework_data$Intensity.lux, na.rm = TRUE) 
  H_data$stdev_light[i] <- sd(homework_data$Intensity.lux, na.rm = TRUE)}
head(H_data) 
```
# On to Purr #
```{r}
H_files2 <- dir(path = H_path, pattern = ".csv", full.names = TRUE) 
H_data2<-H_files2 %>% 
  set_names()%>%  
  map_df(read_csv,.id = "filename") %>% 
  group_by(filename) %>% 
  summarise(mean_temp = mean(Temp.C, na.rm = TRUE),  
            stdev_temp = sd(Temp.C, na.rm = TRUE), 
            mean_light = mean(Intensity.lux, na.rm = TRUE), 
            stdev_light = sd(Intensity.lux, na.rm = TRUE))
head(H_data2)  
```


