---
title: "Week 12.1 Script"
author: "Manroop"
date: "4/19/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, fig.path = "../Output/")
```

# Load Libraries #
```{r}
library(here)
library(tidyverse)
library(tidytext)
library(wordcloud2)
library(janeaustenr)
```

#Stringer#

```{r}

words<-
words
words_vector<-c("Apples", "Bananas","Oranges")
words_vector
paste("High temp", "Low pH", sep = "-")
paste0("High temp", "Low pH")
shapes <- c("Square", "Circle", "Triangle")
paste("My favorite shape is a", shapes)
two_cities <- c("best", "worst")
paste("It was the", two_cities, "of times.")

shapes 
str_length(shapes) 
seq_data<-c("ATCCCGTC")
str_sub(seq_data, start = 2, end = 4) 
str_sub(seq_data, start = 3, end = 3) <- "A" 
seq_data
str_dup(seq_data, times = c(2, 3)) 
badtreatments<-c("High", " High", "High ", "Low", "Low")
badtreatments
str_trim(badtreatments) 
str_trim(badtreatments, side = "left") 
str_pad(badtreatments, 5, side = "right")
str_pad(badtreatments, 5, side = "right", pad = "1") 
x<-"I love R"
str_to_upper(x)
str_to_lower(x) 
str_to_title(x) 


data<-c("AAA", "TATA", "CTAG", "GCTT")
str_view(data, pattern = "A") 
str_detect(data, pattern = "A")
str_detect(data, pattern = "AT")
str_locate(data, pattern = "AT")
vals<-c("a.b", "b.c","c.d")
str_replace(vals, "\\.", " ") 
val2<-c("test 123", "test 456", "test")
str_subset(val2, "\\d")
str_count(val2, "[aeiou]")
str_count(val2, "[0-9]")


strings<-c("550-153-7578",
         "banana",
         "435.114.7586",
         "home: 672-442-6739")
phone <- "([2-9][0-9]{2})[- .]([0-9]{3})[- .]([0-9]{4})"
str_detect(strings, phone) 
test<-str_subset(strings, phone)  
test

test %>%
  str_replace_all("\\.", "-") %>%
  str_replace_all("[a-z]", "") %>%
  str_replace_all("[:]", "") %>%
  str_trim()
test %>%
  str_replace_all(pattern = "\\.", replacement = "-") %>% 
  str_replace_all(pattern = "[a-zA-Z]|\\:", replacement = "") %>%
  str_trim() 

head(austen_books()) 
tail(austen_books())
original_books <- austen_books() %>%
  group_by(book) %>%
  mutate(line = row_number(), 
         chapter = cumsum(str_detect(text, regex("^chapter [\\divxlc]", 
  ignore_case = TRUE)))) %>% 
  ungroup() 
head(original_books)
tidy_books <- original_books %>%
  unnest_tokens(output = word, input = text) 
head(tidy_books) 
head(get_stopwords()) 
cleaned_books <- tidy_books %>%
  anti_join(get_stopwords()) 
head(cleaned_books)
cleaned_books %>%
  count(word, sort = TRUE)
sent_word_counts <- tidy_books %>%
  inner_join(get_sentiments()) %>% 
  count(word, sentiment, sort = TRUE) 
sent_word_counts %>%
  filter(n > 150) %>% 
  mutate(n = ifelse(sentiment == "negative", -n, n)) %>% 
  mutate(word = reorder(word, n)) %>% 
  ggplot(aes(word, n, fill = sentiment)) +
  geom_col() +
  coord_flip() +
  labs(y = "Contribution to sentiment")
words<-cleaned_books %>%
  count(word) %>% 
  arrange(desc(n))%>%
  slice(1:100)
wordcloud2(words, shape = 'triangle', size=0.3)
```
