---
title: "Week 7.1 Script"
author: "Manroop"
date: "3/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path= "../Output/",waring=FALSE, message=FALSE)  
```

# Load Libraries #
```{r, message=FALSE, warning=FALSE}
# Load libraries
library(tidyverse)
library(here)
library(maps)
library(mapdata)
library(mapproj)
install.packages(c("maps", "mapproj"))
```

# Data #
```{r}
popdata<-read_csv(here("Week_7","data","CApopdata.csv"))
stars<-read_csv(here("Week_7","data","stars.csv"))
```

# Working with Maps Package #
```{r}
world<-map_data("world")
usa<-map_data("usa")
head(usa)
italy<-map_data("italy")
head(italy)
states<-map_data("state")
head(states)
counties<-map_data("county")
head(counties)
```
# Creating a World Map #
```{r}
ggplot()+
  geom_polygon(data = world, 
               aes(x = long,
                   y = lat,
                   group = group, 
                   fill = region),
               color = "black")+
  theme_minimal()+
  guides(fill = FALSE)+
  theme(panel.background = element_rect(fill = "lightblue"))+
  coord_map(projection = "sinusoidal",
            xlim = c(-180,180))
```

# California Map #
```{r}
CA_data<-states %>%
  filter(region == "california")
ggplot()+
geom_polygon(data = CA_data, 
             aes(x = long, 
                 y = lat, 
                 group = group), 
             color = "pink")+
  coord_map()+
  theme_void()
```
# CA County Map #
```{r}
head(counties)[1:3,]
head(popdata)
CApop_county<-popdata %>%
  select("subregion" = County, Population)  %>% 
  inner_join(counties) %>%
  filter(region == "california")
head(CApop_county)
ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),
             color = "black")+
   geom_point(data = stars,
             aes(x = long,
                 y = lat))+
  coord_map()+
  theme_void() +
  scale_fill_gradient(trans = "log10")+
  labs(size = "# stars/m2")
head(stars)
 ggsave(here("Week_7","Output","CApop.pdf"))

```



